name: Chromatic CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      # ... other step
      - uses: actions/checkout@v4
      - name: yarn install
        run: yarn install
      - run: ls
      - run: pwd
      - name: Publish Project 1 to Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: chpt_baaa92a29d8b0e1
          onlyChanged: true # 👈 Required option to enable TurboSnap
          workingDir: packages/fuselage-toastbar

