name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-test:
    name: Build and Test
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.job }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run ci
      - uses: actions/upload-artifact@v2
        with:
          name: "storybooks-${{ github.event.number }}"
          path: |
            packages/fuselage/storybook-static
            packages/fuselage-ui-kit/storybook-static
            packages/onboarding-ui/storybook-static
  # test-with-loki:
  #   name: Test with Loki
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-and-test
  #   steps:
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14.17.6"
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       id: yarn-cache
  #       with:
  #         path: |
  #           **/node_modules
  #           .yarn/cache
  #         key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
  #     - run: yarn install
  #       if: steps.yarn-cache.outputs.cache-hit != 'true'
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: "storybooks-${{ github.event.number }}"
  #         path: packages
  #     - name: Turbo Cache
  #       id: turbo-cache
  #       uses: actions/cache@v2
  #       with:
  #         path: .turbo
  #         key: turbo-${{ runner.os }}-${{ github.job }}
  #         restore-keys: |
  #           turbo-${{ runner.os }}-
  #     - uses: ./.github/actions/loki/test

  storycap:
    name: Storycap
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - uses: actions/download-artifact@v2
        with:
          name: "storybooks-${{ github.event.number }}"
          path: packages
      - name: Turbo Cache
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.job }}
          restore-keys: |
            turbo-${{ runner.os }}-
      # - uses: ./.github/actions/storycap
      - run: |
          git config user.email "support@rocket.chat"
          git config user.name "Rocket.Chat"
      # - name: workaround for detached HEAD
      #   run: |
      #     git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: capture snapshots
        run: |
          yarn workspace @rocket.chat/fuselage storycap http://127.0.0.1:8080 --serverCmd "npx http-server storybook-static"
      - name: run reg-suit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: yarn run storycap:test
